[package]
org = "ballerinax"
name = "nats"
version = "3.3.2"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub", "Vendor/NATS", "Area/Messaging", "Type/Connector", "Type/Trigger"]
repository = "https://github.com/ballerina-platform/module-ballerinax-nats"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.14.0-20260527-050400-74f7e6bf"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
path = "./lib/jnats-2.20.4.jar"

[[platform.java25.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "nats-native"
version = "3.3.2"
path = "../native/build/libs/nats-native-3.3.2-SNAPSHOT.jar"

[[platform.java25.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.7.0"
path = "./lib/constraint-native-1.7.0.jar"

[build-options]
observabilityIncluded=true
